//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifpa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifpa.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagpedia.
        /// </summary>
        internal static string AboutPage_Flagpedia {
            get {
                return ResourceManager.GetString("AboutPage_Flagpedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for the country flag icons used in the app.
        /// </summary>
        internal static string AboutPage_Flagpedia_ForFlags {
            get {
                return ResourceManager.GetString("AboutPage_Flagpedia_ForFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to .
        /// </summary>
        internal static string AboutPage_Flagpedia_ThanksTo {
            get {
                return ResourceManager.GetString("AboutPage_Flagpedia_ThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string AboutPage_LearnMore {
            get {
                return ResourceManager.GetString("AboutPage_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a Review.
        /// </summary>
        internal static string AboutPage_LeaveAReview {
            get {
                return ResourceManager.GetString("AboutPage_LeaveAReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET MAUI.
        /// </summary>
        internal static string AboutPage_NetMaui {
            get {
                return ResourceManager.GetString("AboutPage_NetMaui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you to the Github Sponsors!.
        /// </summary>
        internal static string AboutPage_Thanks_Sponsors {
            get {
                return ResourceManager.GetString("AboutPage_Thanks_Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is written in C# and native APIs using.
        /// </summary>
        internal static string AboutPage_ThisPageWrittenIn {
            get {
                return ResourceManager.GetString("AboutPage_ThisPageWrittenIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app was written by .
        /// </summary>
        internal static string AboutPage_WrittenBy {
            get {
                return ResourceManager.GetString("AboutPage_WrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All Seen.
        /// </summary>
        internal static string ActivityFeedPage_MarkAllSeen {
            get {
                return ResourceManager.GetString("ActivityFeedPage_MarkAllSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Feed.
        /// </summary>
        internal static string ActivityFeedPage_Title {
            get {
                return ResourceManager.GetString("ActivityFeedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFPA.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFPA Companion.
        /// </summary>
        internal static string AppName_Full {
            get {
                return ResourceManager.GetString("AppName_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Calendar.
        /// </summary>
        internal static string CalendarDetail_AddToCalendar {
            get {
                return ResourceManager.GetString("CalendarDetail_AddToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string CalendarDetail_Date {
            get {
                return ResourceManager.GetString("CalendarDetail_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director:.
        /// </summary>
        internal static string CalendarDetail_Director {
            get {
                return ResourceManager.GetString("CalendarDetail_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string CalendarDetail_Share {
            get {
                return ResourceManager.GetString("CalendarDetail_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string CalendarFilter_Distance {
            get {
                return ResourceManager.GetString("CalendarFilter_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Events.
        /// </summary>
        internal static string CalendarFilter_FindEvents {
            get {
                return ResourceManager.GetString("CalendarFilter_FindEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string CalendarFilter_Location {
            get {
                return ResourceManager.GetString("CalendarFilter_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi.
        /// </summary>
        internal static string Units_MilesAbbreviation {
            get {
                return ResourceManager.GetString("Units_MilesAbbreviation", resourceCulture);
            }
        }
    }
}
